delete from t_report;
delete from t_iot;
delete from t_request;
delete from t_user;

INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 01', 'user_pw 01', 'user_name 01', 'user_phone 01', 'user_email 01', 'user_addr 01', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 02', 'user_pw 02', 'user_name 02', 'user_phone 02', 'user_email 02', 'user_addr 02', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 03', 'user_pw 03', 'user_name 03', 'user_phone 03', 'user_email 03', 'user_addr 03', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 04', 'user_pw 04', 'user_name 04', 'user_phone 04', 'user_email 04', 'user_addr 04', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 05', 'user_pw 05', 'user_name 05', 'user_phone 05', 'user_email 05', 'user_addr 05', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 06', 'user_pw 06', 'user_name 06', 'user_phone 06', 'user_email 06', 'user_addr 06', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 07', 'user_pw 07', 'user_name 07', 'user_phone 07', 'user_email 07', 'user_addr 07', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 08', 'user_pw 08', 'user_name 08', 'user_phone 08', 'user_email 08', 'user_addr 08', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 09', 'user_pw 09', 'user_name 09', 'user_phone 09', 'user_email 09', 'user_addr 09', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 10', 'user_pw 10', 'user_name 10', 'user_phone 10', 'user_email 10', 'user_addr 10', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 11', 'user_pw 11', 'user_name 11', 'user_phone 11', 'user_email 11', 'user_addr 11', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 12', 'user_pw 12', 'user_name 12', 'user_phone 12', 'user_email 12', 'user_addr 12', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 13', 'user_pw 13', 'user_name 13', 'user_phone 13', 'user_email 13', 'user_addr 13', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 14', 'user_pw 14', 'user_name 14', 'user_phone 14', 'user_email 14', 'user_addr 14', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 15', 'user_pw 15', 'user_name 15', 'user_phone 15', 'user_email 15', 'user_addr 15', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 16', 'user_pw 16', 'user_name 16', 'user_phone 16', 'user_email 16', 'user_addr 16', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 17', 'user_pw 17', 'user_name 17', 'user_phone 17', 'user_email 17', 'user_addr 17', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 18', 'user_pw 18', 'user_name 18', 'user_phone 18', 'user_email 18', 'user_addr 18', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 19', 'user_pw 19', 'user_name 19', 'user_phone 19', 'user_email 19', 'user_addr 19', 'N', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('user_id 20', 'user_pw 20', 'user_name 20', 'user_phone 20', 'user_email 20', 'user_addr 20', 'N', sysdate);

drop trigger t_iot_AI_TRG;

INSERT INTO t_iot (product_seq,product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES (t_iot_SEQ.NEXTVAL,'product_uid 01', 'product_loc 01', 01, 01, sysdate, 'user_id 01');
INSERT INTO t_iot (product_seq,product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES (t_iot_SEQ.NEXTVAL,'product_uid 02', 'product_loc 02', 02, 02, sysdate, 'user_id 02');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 03', 'product_loc 03', 03, 03, sysdate, 'user_id 03');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 04', 'product_loc 04', 04, 04, sysdate, 'user_id 04');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 05', 'product_loc 05', 05, 05, sysdate, 'user_id 05');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 06', 'product_loc 06', 06, 06, sysdate, 'user_id 06');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 07', 'product_loc 07', 07, 07, sysdate, 'user_id 07');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 08', 'product_loc 08', 08, 08, sysdate, 'user_id 08');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 09', 'product_loc 09', 09, 09, sysdate, 'user_id 09');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 10', 'product_loc 10', 10, 10, sysdate, 'user_id 10');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 11', 'product_loc 11', 11, 11, sysdate, 'user_id 11');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 12', 'product_loc 12', 12, 12, sysdate, 'user_id 12');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 13', 'product_loc 13', 13, 13, sysdate, 'user_id 13');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 14', 'product_loc 14', 14, 14, sysdate, 'user_id 14');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 15', 'product_loc 15', 15, 15, sysdate, 'user_id 15');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 16', 'product_loc 16', 16, 16, sysdate, 'user_id 16');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 17', 'product_loc 17', 17, 17, sysdate, 'user_id 17');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 18', 'product_loc 18', 18, 18, sysdate, 'user_id 18');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 19', 'product_loc 19', 19, 19, sysdate, 'user_id 19');
INSERT INTO t_iot (product_uid, product_loc, product_latitude, product_longitude, product_date, user_id) VALUES ('product_uid 20', 'product_loc 20', 20, 20, sysdate, 'user_id 20');
select * from T_USER;

INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('admin', '1', 'user_name 1', 'user_phone 1', 'user_email 1', 'user_addr 1', 'Y', sysdate);
INSERT INTO t_user (user_id, user_pw, user_name, user_phone, user_email, user_addr, admin_yn, user_joindate) VALUES ('admin1', '1', 'user_name 2', 'user_phone 2', 'user_email 2', 'user_addr 2', 'Y', sysdate);